[workspace]
authors = ["indexofire <indexofire@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "hermes-bacmap"
platforms = ["linux-64"]
version = "0.5.0"

[tasks]

[dependencies]
python = "3.12.*"
samtools = ">=1.20"
bwa = ">=0.7.17"
minimap2 = ">=2.28"
bcftools = ">=1.20"
blast = ">=2.16"
bedtools = ">=2.31"
seqkit = ">=2.8"
sra-tools = ">=3.0"
spades = ">=3.15"
openjdk = ">=11,<17"
shovill = ">=1.1.0,<2"
snakemake = "7.32.*"
sistr_cmd = ">=1.1.3,<2"
fastp = ">=1.3.5,<2"
abricate = ">=1.4.0,<2"
iqtree = ">=3.1.2,<4"
prodigal = ">=2.6.3,<3"

[pypi-dependencies]
gmlst = ">=0.1.0"
